# Generated by Django 5.1 on 2024-08-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempApp', '0002_alter_temperaturereading_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumidityReading',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('humidity', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
